# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
  auto_detect_solc = false
  bytecode_hash = "none"
  evm_version = "cancun"
  fuzz = { runs = 1_000 }
  invariant = { runs = 100, depth = 100 }
  gas_reports = ["*"]
  optimizer = true
  via_ir = true
  optimizer_runs = 100000
  out = "out"
  script = "script"
  solc = "0.8.29"
  src = "src"
  test = "test"
  fs_permissions = [
    { access = "read-write", path = "./" },
  ]

[profile.lite]
optimizer = false
via_ir = false

[profile.ci]
  fuzz = { runs = 10_000 }
  verbosity = 3 # outputs stack trace for failed tests only (https://book.getfoundry.sh/reference/config/testing)

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "attributes_first"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true
  sort_imports = true

[profile.cancun_1000_ir]
  auto_detect_solc = false
  bytecode_hash = "none"
  evm_version = "cancun"
  fuzz = { runs = 1_000 }
  invariant = { runs = 100, depth = 100 }
  gas_reports = ["*"]
  optimizer = true
  via_ir = true
  optimizer_runs = 25_000
  out = "out"
  script = "script"
  solc = "0.8.29"
  src = "src"
  test = "test"
  fs_permissions = [
    { access = "read-write", path = "./" },
  ]